- name: conditions
  hosts: localhost
  connection: local
  vars:
    number: 5
  tasks:
  - name: check if the number is greater than 10 or not
    ansible.builtin.debug:
      msg: "given number is {{ number }} less than 10"
    when: number < 10
