- name: datatypes in ansible
  hosts: localhost
  connection: local
  vars:
    course: ansible
    duration: 12hrs
    is_live: true
    tools:
    - ansible
    - shell
    - devops
    concepts:
      cloud: aws
      cmd: ansible
  tasks:
  - name: print the datatypes
    ansible.builtin.debug:
      msg: " coursename: {{ course }}, duration: {{ duration }}, is live: {{ is_live }}, tools are: {{ tools }}, concepts are: {{ concepts }}"