- name: loops
  hosts: localhost
  connection: local
  tasks:
  - name: print loops
    ansible.builtin.debug:
      msg: "hello {{ item }}"
    loops:
    - saikiran
    - lakshmi 
    - durga
    - dhaswika
    