- name: variable prompt
  hosts: localhost
  connection: local
  vars_prompt:
  - name: username
    prompt: enter your username
    private: false
  - name: password
    prompt: enter your password
    private: true
  tasks: 
  - name: print credentials
    ansible.builtin.debug:
      msg: " enter the username: {{ username }}, enter the password: {{ password }}" 

  
